use crate::hexchess::position::Position;
use std::fmt;

/// Initial game position
pub const INITIAL_POSITION: &str = "b/qbk/n1b1n/r5r/ppppppppp/11/5P5/4P1P4/3P1B1P3/2P2B2P2/1PRNQBKNRP1 w - 0 1";

/// This graph represents the Position::N hexboard, and their relationship
/// to one another. Each child in the graph represents a Position::ITHt's
/// neighboring Position::ISTEDlockwise starting from the Position::RECTLY// above it.
/// 
/// Think of it like the hands of a clock, with 12 o'clock being index 0...
/// For example, to find the Position::RECTLYelow f6, we'd first go to that
/// Position:: THEen (index 30), then look at the 6th index of that array,
/// which is 41. The 41st fen index is f5.
pub fn hexboard_graph(position: Position) -> [Option<Position>; 12] {
    match position {
        Position::F11 => [
            None, 
            None, 
            None,
            None, 
            Some(Position::G10),
            Some(Position::G9),
            Some(Position::F10),
            Some(Position::E9),
            Some(Position::E10),
            None, 
            None, 
            None
        ],
        Position::E10 => [
            None, 
            None, 
            Some(Position::F11),
            Some(Position::G10),
            Some(Position::F10),
            Some(Position::F9),
            Some(Position::E9),
            Some(Position::D8),
            Some(Position::D9),
            None, 
            None, 
            None
],
        Position::F10 => [
            Some(Position::F11),
            None, 
            Some(Position::G10),
            Some(Position::H9),
            Some(Position::G9),
            Some(Position::G8),
            Some(Position::F9),
            Some(Position::E8),
            Some(Position::E9),
            Some(Position::D9),
            Some(Position::E10),
            None,
        ],
        Position::G10 => [
            None, 
            None, 
            None,
            None, 
            Some(Position::H9),
            Some(Position::H8),
            Some(Position::G9),
            Some(Position::F9),
            Some(Position::F10),
            Some(Position::E10),
            Some(Position::F11),
            None,
        ],
        Position::D9 => [
            None, 
            None,
            Some(Position::E10),
            Some(Position::F10),
            Some(Position::E9),
            Some(Position::E8),
            Some(Position::D8),
            Some(Position::C7),
            Some(Position::C8),
            None, 
            None,
            None
        ],
        Position::E9 => [
            Some(Position::E10),
            Some(Position::F11),
            Some(Position::F10),
            Some(Position::G9),
            Some(Position::F9),
            Some(Position::F8),
            Some(Position::E8),
            Some(Position::D7),
            Some(Position::D8),
            Some(Position::C8),
            Some(Position::D9), 
            None
        ],
        Position::F9 => [
            Some(Position::F10),
            Some(Position::G10),
            Some(Position::G9),
            Some(Position::H8),
            Some(Position::G8),
            Some(Position::G7),
            Some(Position::F8),
            Some(Position::E7),
            Some(Position::E8),
            Some(Position::D8),
            Some(Position::E9),
            Some(Position::E10)
        ],
        Position::G9 => [
            Some(Position::G10),
            None, 
            Some(Position::H9),
            Some(Position::I8),
            Some(Position::H8),
            Some(Position::H7),
            Some(Position::G8),
            Some(Position::F8),
            Some(Position::F9),
            Some(Position::E9),
            Some(Position::F10),
            Some(Position::F11)
        ],
        Position::H9 => [
            None, 
            None, 
            None,
            None, 
            Some(Position::I8),
            Some(Position::I7),
            Some(Position::H8),
            Some(Position::G8),
            Some(Position::G9),
            Some(Position::F10),
            Some(Position::G10),
            None,
        ],
        Position::C8 => [
            None,
            None,
            Some(Position::D9),
            Some(Position::E9),
            Some(Position::D8),
            Some(Position::D7),
            Some(Position::C7),
            Some(Position::B6),
            Some(Position::B7),
            None,
            None,
            None
        ],
        Position::D8 => [
            Some(Position::D9),
            Some(Position::E10),
            Some(Position::E9),
            Some(Position::F9),
            Some(Position::E8),
            Some(Position::E7),
            Some(Position::D7),
            Some(Position::C6),
            Some(Position::C7),
            Some(Position::B7),
            Some(Position::C8), 
            None
        ],
        Position::E8 => [
            Some(Position::E9),
            Some(Position::F10),
            Some(Position::F9),
            Some(Position::G8),
            Some(Position::F8),
            Some(Position::F7),
            Some(Position::E7),
            Some(Position::D6),
            Some(Position::D7),
            Some(Position::C7),
            Some(Position::D8),
            Some(Position::D9)
        ],
        Position::F8 => [
            Some(Position::F9),
            Some(Position::G9),
            Some(Position::G8),
            Some(Position::H7),
            Some(Position::G7),
            Some(Position::G6),
            Some(Position::F7),
            Some(Position::E6),
            Some(Position::E7),
            Some(Position::D7),
            Some(Position::E8),
            Some(Position::E9)
        ],
        Position::G8 => [
            Some(Position::G9),
            Some(Position::H9),
            Some(Position::H8),
            Some(Position::I7),
            Some(Position::H7),
            Some(Position::H6),
            Some(Position::G7),
            Some(Position::F7),
            Some(Position::F8),
            Some(Position::E8),
            Some(Position::F9),
            Some(Position::F10)
        ],
        Position::H8 => [
            Some(Position::H9),
            None,
            Some(Position::I8),
            Some(Position::K7),
            Some(Position::I7),
            Some(Position::I6),
            Some(Position::H7),
            Some(Position::G7),
            Some(Position::G8),
            Some(Position::F9),
            Some(Position::G9),
            Some(Position::G10)
        ],
        Position::I8 => [
            None,
            None,
            None,
            None,
            Some(Position::K7),
            Some(Position::K6),
            Some(Position::I7),
            Some(Position::H7),
            Some(Position::H8),
            Some(Position::G9),
            Some(Position::H9),
            None,
        ],
        Position::B7 => [
            None,
            None,
            Some(Position::C8),
            Some(Position::D8),
            Some(Position::C7),
            Some(Position::C6),
            Some(Position::B6),
            Some(Position::A5),
            Some(Position::A6),
            None,
            None,
            None
        ],
        Position::C7 => [
            Some(Position::C8),
            Some(Position::D9),
            Some(Position::D8),
            Some(Position::E8),
            Some(Position::D7),
            Some(Position::D6),
            Some(Position::C6),
            Some(Position::B5),
            Some(Position::B6),
            Some(Position::A6),
            Some(Position::B7),
            None,
        ],
        Position::D7 => [
            Some(Position::D8),
            Some(Position::E9),
            Some(Position::E8),
            Some(Position::F8),
            Some(Position::E7),
            Some(Position::E6),
            Some(Position::D6),
            Some(Position::C5),
            Some(Position::C6),
            Some(Position::B6),
            Some(Position::C7),
            Some(Position::C8)
        ],
        Position::E7 => [
            Some(Position::E8),
            Some(Position::F9),
            Some(Position::F8),
            Some(Position::G7),
            Some(Position::F7),
            Some(Position::F6),
            Some(Position::E6),
            Some(Position::D5),
            Some(Position::D6),
            Some(Position::C6),
            Some(Position::D7),
            Some(Position::D8)
        ],
        Position::F7 => [
            Some(Position::F8),
            Some(Position::G8),
            Some(Position::G7),
            Some(Position::H6),
            Some(Position::G6),
            Some(Position::G5),
            Some(Position::F6),
            Some(Position::E5),
            Some(Position::E6),
            Some(Position::D6),
            Some(Position::E7),
            Some(Position::E8)
        ],
        Position::G7 => [
            Some(Position::G8),
            Some(Position::H8),
            Some(Position::H7),
            Some(Position::I6),
            Some(Position::H6),
            Some(Position::H5),
            Some(Position::G6),
            Some(Position::F6),
            Some(Position::F7),
            Some(Position::E7),
            Some(Position::F8),
            Some(Position::F9)
        ],
        Position::H7 => [
            Some(Position::H8),
            Some(Position::I8),
            Some(Position::I7),
            Some(Position::K6),
            Some(Position::I6),
            Some(Position::I5),
            Some(Position::H6),
            Some(Position::G6),
            Some(Position::G7),
            Some(Position::F8),
            Some(Position::G8),
            Some(Position::G9)
        ],
        Position::I7 => [
            Some(Position::I8),
            None,
            Some(Position::K7),
            Some(Position::L6),
            Some(Position::K6),
            Some(Position::K5),
            Some(Position::I6),
            Some(Position::H6),
            Some(Position::H7),
            Some(Position::G8),
            Some(Position::H8),
            Some(Position::H9)
        ],
        Position::K7 => [
            None,
            None,
            None,
            None,
            Some(Position::L6),
            Some(Position::L5),
            Some(Position::K6),
            Some(Position::I6),
            Some(Position::I7),
            Some(Position::H8),
            Some(Position::I8),
            None,
        ],
        Position::A6 => [
            None,
            None,
            Some(Position::B7),
            Some(Position::C7),
            Some(Position::B6),
            Some(Position::B5),
            Some(Position::A5),
            None,
            None,
            None,
            None,
            None
        ],
        Position::B6 => [
            Some(Position::B7),
            Some(Position::C8),
            Some(Position::C7),
            Some(Position::D7),
            Some(Position::C6),
            Some(Position::C5),
            Some(Position::B5),
            Some(Position::A4),
            Some(Position::A5),
            None,
            Some(Position::A6),
            None,
        ],
        Position::C6 => [
            Some(Position::C7),
            Some(Position::D8),
            Some(Position::D7),
            Some(Position::E7),
            Some(Position::D6),
            Some(Position::D5),
            Some(Position::C5),
            Some(Position::B4),
            Some(Position::B5),
            Some(Position::A5),
            Some(Position::B6),
            Some(Position::B7)
        ],
        Position::D6 => [
            Some(Position::D7),
            Some(Position::E8),
            Some(Position::E7),
            Some(Position::F7),
            Some(Position::E6),
            Some(Position::E5),
            Some(Position::D5),
            Some(Position::C4),
            Some(Position::C5),
            Some(Position::B5),
            Some(Position::C6),
            Some(Position::C7)
        ],
        Position::E6 => [
            Some(Position::E7),
            Some(Position::F8),
            Some(Position::F7),
            Some(Position::G6),
            Some(Position::F6),
            Some(Position::F5),
            Some(Position::E5),
            Some(Position::D4),
            Some(Position::D5),
            Some(Position::C5),
            Some(Position::D6),
            Some(Position::D7)
        ],
        Position::F6 => [
            Some(Position::F7),
            Some(Position::G7),
            Some(Position::G6),
            Some(Position::H5),
            Some(Position::G5),
            Some(Position::G4),
            Some(Position::F5),
            Some(Position::E4),
            Some(Position::E5),
            Some(Position::D5),
            Some(Position::E6),
            Some(Position::E7)
        ],
        Position::G6 => [
            Some(Position::G7),
            Some(Position::H7),
            Some(Position::H6),
            Some(Position::I5),
            Some(Position::H5),
            Some(Position::H4),
            Some(Position::G5),
            Some(Position::F5),
            Some(Position::F6),
            Some(Position::E6),
            Some(Position::F7),
            Some(Position::F8)
        ],
        Position::H6 => [
            Some(Position::H7),
            Some(Position::I7),
            Some(Position::I6),
            Some(Position::K5),
            Some(Position::I5),
            Some(Position::I4),
            Some(Position::H5),
            Some(Position::G5),
            Some(Position::G6),
            Some(Position::F7),
            Some(Position::G7),
            Some(Position::G8)
        ],
        Position::I6 => [
            Some(Position::I7),
            Some(Position::K7),
            Some(Position::K6),
            Some(Position::L5),
            Some(Position::K5),
            Some(Position::K4),
            Some(Position::I5),
            Some(Position::H5),
            Some(Position::H6),
            Some(Position::G7),
            Some(Position::H7),
            Some(Position::H8)
        ],
        Position::K6 => [
            Some(Position::K7),
            None,
            Some(Position::L6),
            None,
            Some(Position::L5),
            Some(Position::L4),
            Some(Position::K5),
            Some(Position::I5),
            Some(Position::I6),
            Some(Position::H7),
            Some(Position::I7),
            Some(Position::I8)
        ],
        Position::L6 => [
            None,
            None,
            None,
            None,
            None,
            None,
            Some(Position::L5),
            Some(Position::K5),
            Some(Position::K6),
            Some(Position::I7),
            Some(Position::K7),
            None,
        ],
        Position::A5 => [
            Some(Position::A6),
            Some(Position::B7),
            Some(Position::B6),
            Some(Position::C6),
            Some(Position::B5),
            Some(Position::B4),
            Some(Position::A4),
            None,
            None,
            None,
            None,
            None
        ],
        Position::B5 => [
            Some(Position::B6),
            Some(Position::C7),
            Some(Position::C6),
            Some(Position::D6),
            Some(Position::C5),
            Some(Position::C4),
            Some(Position::B4),
            Some(Position::A3),
            Some(Position::A4),
            None,
            Some(Position::A5),
            Some(Position::A6)
        ],
        Position::C5 => [
            Some(Position::C6),
            Some(Position::D7),
            Some(Position::D6),
            Some(Position::E6),
            Some(Position::D5),
            Some(Position::D4),
            Some(Position::C4),
            Some(Position::B3),
            Some(Position::B4),
            Some(Position::A4),
            Some(Position::B5),
            Some(Position::B6)
        ],
        Position::D5 => [
            Some(Position::D6),
            Some(Position::E7),
            Some(Position::E6),
            Some(Position::F6),
            Some(Position::E5),
            Some(Position::E4),
            Some(Position::D4),
            Some(Position::C3),
            Some(Position::C4),
            Some(Position::B4),
            Some(Position::C5),
            Some(Position::C6)
        ],
        Position::E5 => [
            Some(Position::E6),
            Some(Position::F7),
            Some(Position::F6),
            Some(Position::G5),
            Some(Position::F5),
            Some(Position::F4),
            Some(Position::E4),
            Some(Position::D3),
            Some(Position::D4),
            Some(Position::C4),
            Some(Position::D5),
            Some(Position::D6)
        ],
        Position::F5 => [
            Some(Position::F6),
            Some(Position::G6),
            Some(Position::G5),
            Some(Position::H4),
            Some(Position::G4),
            Some(Position::G3),
            Some(Position::F4),
            Some(Position::E3),
            Some(Position::E4),
            Some(Position::D4),
            Some(Position::E5),
            Some(Position::E6)
        ],
        Position::G5 => [
            Some(Position::G6),
            Some(Position::H6),
            Some(Position::H5),
            Some(Position::I4),
            Some(Position::H4),
            Some(Position::H3),
            Some(Position::G4),
            Some(Position::F4),
            Some(Position::F5),
            Some(Position::E5),
            Some(Position::F6),
            Some(Position::F7)
        ],
        Position::H5 => [
            Some(Position::H6),
            Some(Position::I6),
            Some(Position::I5),
            Some(Position::K4),
            Some(Position::I4),
            Some(Position::I3),
            Some(Position::H4),
            Some(Position::G4),
            Some(Position::G5),
            Some(Position::F6),
            Some(Position::G6),
            Some(Position::G7)
        ],
        Position::I5 => [
            Some(Position::I6),
            Some(Position::K6),
            Some(Position::K5),
            Some(Position::L4),
            Some(Position::K4),
            Some(Position::K3),
            Some(Position::I4),
            Some(Position::H4),
            Some(Position::H5),
            Some(Position::G6),
            Some(Position::H6),
            Some(Position::H7)
        ],
        Position::K5 => [
            Some(Position::K6),
            Some(Position::L6),
            Some(Position::L5),
            None,
            Some(Position::L4),
            Some(Position::L3),
            Some(Position::K4),
            Some(Position::I4),
            Some(Position::I5),
            Some(Position::H6),
            Some(Position::I6),
            Some(Position::I7)
        ],
        Position::L5 => [
            Some(Position::L6),
            None,
            None,
            None,
            None,
            None,
            Some(Position::L4),
            Some(Position::K4),
            Some(Position::K5),
            Some(Position::I6),
            Some(Position::K6),
            Some(Position::K7)
        ],
        Position::A4 => [
            Some(Position::A5),
            Some(Position::B6),
            Some(Position::B5),
            Some(Position::C5),
            Some(Position::B4),
            Some(Position::B3),
            Some(Position::A3),
            None,
            None,
            None,
            None,
            None
        ],
        Position::B4 => [
            Some(Position::B5),
            Some(Position::C6),
            Some(Position::C5),
            Some(Position::D5),
            Some(Position::C4),
            Some(Position::C3),
            Some(Position::B3),
            Some(Position::A2),
            Some(Position::A3),
            None,
            Some(Position::A4),
            Some(Position::A5)
        ],
        Position::C4 => [
            Some(Position::C5),
            Some(Position::D6),
            Some(Position::D5),
            Some(Position::E5),
            Some(Position::D4),
            Some(Position::D3),
            Some(Position::C3),
            Some(Position::B2),
            Some(Position::B3),
            Some(Position::A3),
            Some(Position::B4),
            Some(Position::B5)
        ],
        Position::D4 => [
            Some(Position::D5),
            Some(Position::E6),
            Some(Position::E5),
            Some(Position::F5),
            Some(Position::E4),
            Some(Position::E3),
            Some(Position::D3),
            Some(Position::C2),
            Some(Position::C3),
            Some(Position::B3),
            Some(Position::C4),
            Some(Position::C5)
        ],
        Position::E4 => [
            Some(Position::E5),
            Some(Position::F6),
            Some(Position::F5),
            Some(Position::G4),
            Some(Position::F4),
            Some(Position::F3),
            Some(Position::E3),
            Some(Position::D2),
            Some(Position::D3),
            Some(Position::C3),
            Some(Position::D4),
            Some(Position::D5)
        ],
        Position::F4 => [
            Some(Position::F5),
            Some(Position::G5),
            Some(Position::G4),
            Some(Position::H3),
            Some(Position::G3),
            Some(Position::G2),
            Some(Position::F3),
            Some(Position::E2),
            Some(Position::E3),
            Some(Position::D3),
            Some(Position::E4),
            Some(Position::E5)
        ],
        Position::G4 => [
            Some(Position::G5),
            Some(Position::H5),
            Some(Position::H4),
            Some(Position::I3),
            Some(Position::H3),
            Some(Position::H2),
            Some(Position::G3),
            Some(Position::F3),
            Some(Position::F4),
            Some(Position::E4),
            Some(Position::F5),
            Some(Position::F6)
        ],
        Position::H4 => [
            Some(Position::H5),
            Some(Position::I5),
            Some(Position::I4),
            Some(Position::K3),
            Some(Position::I3),
            Some(Position::I2),
            Some(Position::H3),
            Some(Position::G3),
            Some(Position::G4),
            Some(Position::F5),
            Some(Position::G5),
            Some(Position::G6)
        ],
        Position::I4 => [
            Some(Position::I5),
            Some(Position::K5),
            Some(Position::K4),
            Some(Position::L3),
            Some(Position::K3),
            Some(Position::K2),
            Some(Position::I3),
            Some(Position::H3),
            Some(Position::H4),
            Some(Position::G5),
            Some(Position::H5),
            Some(Position::H6)
        ],
        Position::K4 => [
            Some(Position::K5),
            Some(Position::L5),
            Some(Position::L4),
            None,
            Some(Position::L3),
            Some(Position::L2),
            Some(Position::K3),
            Some(Position::I3),
            Some(Position::I4),
            Some(Position::H5),
            Some(Position::I5),
            Some(Position::I6)
        ],
        Position::L4 => [
            Some(Position::L5),
            None,
            None,
            None,
            None,
            None,
            Some(Position::L3),
            Some(Position::K3),
            Some(Position::K4),
            Some(Position::I5),
            Some(Position::K5),
            Some(Position::K6)
        ],
        Position::A3 => [
            Some(Position::A4),
            Some(Position::B5),
            Some(Position::B4),
            Some(Position::C4),
            Some(Position::B3),
            Some(Position::B2),
            Some(Position::A2),
            None,
            None,
            None,
            None,
            None
        ],
        Position::B3 => [
            Some(Position::B4),
            Some(Position::C5),
            Some(Position::C4),
            Some(Position::D4),
            Some(Position::C3),
            Some(Position::C2),
            Some(Position::B2),
            Some(Position::A1),
            Some(Position::A2),
            None,
            Some(Position::A3),
            Some(Position::A4)
        ],
        Position::C3 => [
            Some(Position::C4),
            Some(Position::D5),
            Some(Position::D4),
            Some(Position::E4),
            Some(Position::D3),
            Some(Position::D2),
            Some(Position::C2),
            Some(Position::B1),
            Some(Position::B2),
            Some(Position::A2),
            Some(Position::B3),
            Some(Position::B4)
        ],
        Position::D3 => [
            Some(Position::D4),
            Some(Position::E5),
            Some(Position::E4),
            Some(Position::F4),
            Some(Position::E3),
            Some(Position::E2),
            Some(Position::D2),
            Some(Position::C1),
            Some(Position::C2),
            Some(Position::B2),
            Some(Position::C3),
            Some(Position::C4)
        ],
        Position::E3 => [
            Some(Position::E4),
            Some(Position::F5),
            Some(Position::F4),
            Some(Position::G3),
            Some(Position::F3),
            Some(Position::F2),
            Some(Position::E2),
            Some(Position::D1),
            Some(Position::D2),
            Some(Position::C2),
            Some(Position::D3),
            Some(Position::D4)
        ],
        Position::F3 => [
            Some(Position::F4),
            Some(Position::G4),
            Some(Position::G3),
            Some(Position::H2),
            Some(Position::G2),
            Some(Position::G1),
            Some(Position::F2),
            Some(Position::E1),
            Some(Position::E2),
            Some(Position::D2),
            Some(Position::E3),
            Some(Position::E4)
        ],
        Position::G3 => [
            Some(Position::G4),
            Some(Position::H4),
            Some(Position::H3),
            Some(Position::I2),
            Some(Position::H2),
            Some(Position::H1),
            Some(Position::G2),
            Some(Position::F2),
            Some(Position::F3),
            Some(Position::E3),
            Some(Position::F4),
            Some(Position::F5)
        ],
        Position::H3 => [
            Some(Position::H4),
            Some(Position::I4),
            Some(Position::I3),
            Some(Position::K2),
            Some(Position::I2),
            Some(Position::I1),
            Some(Position::H2),
            Some(Position::G2),
            Some(Position::G3),
            Some(Position::F4),
            Some(Position::G4),
            Some(Position::G5)
        ],
        Position::I3 => [
            Some(Position::I4),
            Some(Position::K4),
            Some(Position::K3),
            Some(Position::L2),
            Some(Position::K2),
            Some(Position::K1),
            Some(Position::I2),
            Some(Position::H2),
            Some(Position::H3),
            Some(Position::G4),
            Some(Position::H4),
            Some(Position::H5)
        ],
        Position::K3 => [
            Some(Position::K4),
            Some(Position::L4),
            Some(Position::L3),
            None,
            Some(Position::L2),
            Some(Position::L1),
            Some(Position::K2),
            Some(Position::I2),
            Some(Position::I3),
            Some(Position::H4),
            Some(Position::I4),
            Some(Position::I5)
        ],
        Position::L3 => [
            Some(Position::L4),
            None,
            None,
            None,
            None,
            None,
            Some(Position::L2),
            Some(Position::K2),
            Some(Position::K3),
            Some(Position::I4),
            Some(Position::K4),
            Some(Position::K5)
        ],
        Position::A2 => [
            Some(Position::A3),
            Some(Position::B4),
            Some(Position::B3),
            Some(Position::C3),
            Some(Position::B2),
            Some(Position::B1),
            Some(Position::A1),
            None,
            None,
            None,
            None,
            None
        ],
        Position::B2 => [
            Some(Position::B3),
            Some(Position::C4),
            Some(Position::C3),
            Some(Position::D3),
            Some(Position::C2),
            Some(Position::C1),
            Some(Position::B1),
            None,
            Some(Position::A1),
            None,
            Some(Position::A2),
            Some(Position::A3)
        ],
        Position::C2 => [
            Some(Position::C3),
            Some(Position::D4),
            Some(Position::D3),
            Some(Position::E3),
            Some(Position::D2),
            Some(Position::D1),
            Some(Position::C1),
            None,
            Some(Position::B1),
            Some(Position::A1),
            Some(Position::B2),
            Some(Position::B3)
        ],
        Position::D2 => [
            Some(Position::D3),
            Some(Position::E4),
            Some(Position::E3),
            Some(Position::F3),
            Some(Position::E2),
            Some(Position::E1),
            Some(Position::D1),
            None,
            Some(Position::C1),
            Some(Position::B1),
            Some(Position::C2),
            Some(Position::C3)
        ],
        Position::E2 => [
            Some(Position::E3),
            Some(Position::F4),
            Some(Position::F3),
            Some(Position::G2),
            Some(Position::F2),
            Some(Position::F1),
            Some(Position::E1),
            None,
            Some(Position::D1),
            Some(Position::C1),
            Some(Position::D2),
            Some(Position::D3)
        ],
        Position::F2 => [
            Some(Position::F3),
            Some(Position::G3),
            Some(Position::G2),
            Some(Position::H1),
            Some(Position::G1),
            None,
            Some(Position::F1),
            None,
            Some(Position::E1),
            Some(Position::D1),
            Some(Position::E2),
            Some(Position::E3)
        ],
        Position::G2 => [
            Some(Position::G3),
            Some(Position::H3),
            Some(Position::H2),
            Some(Position::I1),
            Some(Position::H1),
            None,
            Some(Position::G1),
            Some(Position::F1),
            Some(Position::F2),
            Some(Position::E2),
            Some(Position::F3),
            Some(Position::F4)
        ],
        Position::H2 => [
            Some(Position::H3),
            Some(Position::I3),
            Some(Position::I2),
            Some(Position::K1),
            Some(Position::I1),
            None,
            Some(Position::H1),
            Some(Position::G1),
            Some(Position::G2),
            Some(Position::F3),
            Some(Position::G3),
            Some(Position::G4)
        ],
        Position::I2 => [
            Some(Position::I3),
            Some(Position::K3),
            Some(Position::K2),
            Some(Position::L1),
            Some(Position::K1),
            None,
            Some(Position::I1),
            Some(Position::H1),
            Some(Position::H2),
            Some(Position::G3),
            Some(Position::H3),
            Some(Position::H4)
        ],
        Position::K2 => [
            Some(Position::K3),
            Some(Position::L3),
            Some(Position::L2),
            None,
            Some(Position::L1),
            None,
            Some(Position::K1),
            Some(Position::I1),
            Some(Position::I2),
            Some(Position::H3),
            Some(Position::I3),
            Some(Position::I4)
        ],
        Position::L2 => [
            Some(Position::L3),
            None,
            None,
            None,
            None,
            None,
            Some(Position::L1),
            Some(Position::K1),
            Some(Position::K2),
            Some(Position::I3),
            Some(Position::K3),
            Some(Position::K4)
        ],
        Position::A1 => [
            Some(Position::A2),
            Some(Position::B3),
            Some(Position::B2),
            Some(Position::C2),
            Some(Position::B1),
            None,
            None,
            None,
            None,
            None,
            None,
            None
        ],
        Position::B1 => [
            Some(Position::B2),
            Some(Position::C3),
            Some(Position::C2),
            Some(Position::D2),
            Some(Position::C1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::A1),
            Some(Position::A2)
        ],
        Position::C1 => [
            Some(Position::C2),
            Some(Position::D3),
            Some(Position::D2),
            Some(Position::E2),
            Some(Position::D1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::B1),
            Some(Position::B2)
        ],
        Position::D1 => [
            Some(Position::D2),
            Some(Position::E3),
            Some(Position::E2),
            Some(Position::F2),
            Some(Position::E1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::C1),
            Some(Position::C2)
        ],
        Position::E1 => [
            Some(Position::E2),
            Some(Position::F3),
            Some(Position::F2),
            Some(Position::G1),
            Some(Position::F1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::D1),
            Some(Position::D2)
        ],
        Position::F1 => [
            Some(Position::F2),
            Some(Position::G2),
            Some(Position::G1),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(Position::E1),
            Some(Position::E2)
        ],
        Position::G1 => [
            Some(Position::G2),
            Some(Position::H2),
            Some(Position::H1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::F1),
            Some(Position::E1),
            Some(Position::F2),
            Some(Position::F3)
        ],
        Position::H1 => [
            Some(Position::H2),
            Some(Position::I2),
            Some(Position::I1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::G1),
            Some(Position::F2),
            Some(Position::G2),
            Some(Position::G3)
        ],
        Position::I1 => [
            Some(Position::I2),
            Some(Position::K2),
            Some(Position::K1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::H1),
            Some(Position::G2),
            Some(Position::H2),
            Some(Position::H3)
        ],
        Position::K1 => [
            Some(Position::K2),
            Some(Position::L2),
            Some(Position::L1),
            None,
            None,
            None,
            None,
            None,
            Some(Position::I1),
            Some(Position::H2),
            Some(Position::I2),
            Some(Position::I3)
        ],
        Position::L1 => [
            Some(Position::L2),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(Position::K1),
            Some(Position::I2),
            Some(Position::K2),
            Some(Position::K3)
        ],
    }
}

/// Reachable Position::OR knight from each Position:: THEoard
pub const KNIGHT_GRAPH: [&[u8]; 91] = [
    &[14, 13, 11, 10],
    &[8, 13, 12, 18, 17],
    &[15, 22, 21, 19, 18, 9],
    &[23, 22, 12, 11, 4],
    &[3, 7, 12, 19, 27, 26],
    &[8, 14, 21, 20, 28, 27, 16],
    &[15, 23, 32, 31, 29, 28, 17, 9],
    &[24, 33, 32, 20, 19, 10, 4],
    &[34, 33, 21, 12, 5, 1],
    &[2, 6, 19, 28, 37, 36],
    &[0, 7, 13, 20, 29, 38, 37, 25],
    &[0, 3, 14, 22, 31, 30, 39, 38, 26, 16],
    &[3, 8, 23, 33, 43, 42, 40, 39, 27, 17, 4, 1],
    &[24, 34, 44, 43, 30, 29, 18, 10, 1, 0],
    &[35, 45, 44, 31, 20, 11, 5, 0],
    &[46, 45, 32, 21, 6, 2],
    &[5, 11, 28, 38, 47],
    &[1, 6, 12, 29, 39, 48, 47],
    &[1, 2, 13, 21, 30, 40, 49, 48, 36, 25],
    &[2, 7, 22, 32, 42, 41, 50, 49, 37, 26, 9, 4],
    &[7, 14, 33, 44, 54, 53, 51, 50, 38, 27, 10, 5],
    &[8, 15, 34, 45, 55, 54, 41, 40, 28, 18, 5, 2],
    &[35, 46, 56, 55, 42, 30, 19, 11, 2, 3],
    &[57, 56, 43, 31, 12, 6, 3],
    &[57, 44, 32, 13, 7],
    &[10, 18, 38, 48],
    &[4, 11, 19, 39, 49, 58],
    &[4, 5, 12, 20, 40, 50, 59, 58],
    &[5, 6, 21, 31, 41, 51, 60, 59, 47, 36, 16, 9],
    &[6, 13, 32, 43, 53, 52, 61, 60, 48, 37, 17, 10],
    &[13, 22, 44, 55, 65, 64, 62, 61, 49, 38, 18, 11],
    &[14, 23, 45, 56, 66, 65, 52, 51, 39, 28, 11, 6],
    &[15, 24, 46, 57, 67, 66, 53, 41, 29, 19, 6, 7],
    &[68, 67, 54, 42, 20, 12, 7, 8],
    &[68, 55, 43, 21, 13, 8],
    &[56, 44, 22, 14],
    &[9, 18, 28, 49, 59],
    &[9, 10, 19, 29, 50, 60, 69],
    &[10, 11, 20, 30, 51, 61, 70, 69, 25, 16],
    &[11, 12, 31, 42, 52, 62, 71, 70, 58, 47, 26, 17],
    &[12, 21, 43, 54, 64, 63, 72, 71, 59, 48, 27, 18],
    &[21, 32, 55, 66, 76, 75, 73, 72, 60, 49, 28, 19],
    &[22, 33, 56, 67, 77, 76, 63, 62, 50, 39, 19, 12],
    &[23, 34, 57, 68, 78, 77, 64, 52, 40, 29, 12, 13],
    &[24, 35, 79, 78, 65, 53, 30, 20, 13, 14],
    &[79, 66, 54, 31, 21, 14, 15],
    &[67, 55, 32, 22, 15],
    &[16, 17, 28, 39, 60, 70],
    &[17, 18, 29, 40, 61, 71, 80, 25],
    &[18, 19, 30, 41, 62, 72, 81, 80, 36, 26],
    &[19, 20, 42, 53, 63, 73, 82, 81, 69, 58, 37, 27],
    &[20, 31, 54, 65, 75, 74, 83, 82, 70, 59, 38, 28],
    &[31, 43, 66, 77, 87, 86, 84, 83, 71, 60, 39, 29],
    &[32, 44, 67, 78, 88, 87, 74, 73, 61, 50, 29, 20],
    &[33, 45, 68, 79, 89, 88, 75, 63, 51, 40, 20, 21],
    &[34, 46, 90, 89, 76, 64, 41, 30, 21, 22],
    &[35, 90, 77, 65, 42, 31, 22, 23],
    &[78, 66, 43, 32, 23, 24],
    &[26, 27, 39, 50, 71, 81],
    &[27, 28, 40, 51, 72, 82, 36],
    &[28, 29, 41, 52, 73, 83, 47, 37],
    &[29, 30, 53, 64, 74, 84, 80, 69, 48, 38],
    &[30, 42, 65, 76, 86, 85, 81, 70, 49, 39],
    &[42, 54, 77, 88, 82, 71, 50, 40],
    &[43, 55, 78, 89, 85, 84, 72, 61, 40, 30],
    &[44, 56, 79, 90, 86, 74, 62, 51, 30, 31],
    &[45, 57, 87, 75, 52, 41, 31, 32],
    &[46, 88, 76, 53, 42, 32, 33],
    &[89, 77, 54, 43, 33, 34],
    &[37, 38, 50, 61, 82],
    &[38, 39, 51, 62, 83, 47],
    &[39, 40, 52, 63, 84, 58, 48],
    &[40, 41, 64, 75, 85, 80, 59, 49],
    &[41, 53, 76, 87, 81, 60, 50],
    &[53, 65, 88, 82, 61, 51],
    &[54, 66, 89, 83, 72, 51, 41],
    &[55, 67, 90, 85, 73, 62, 41, 42],
    &[56, 68, 86, 63, 52, 42, 43],
    &[57, 87, 64, 53, 43, 44],
    &[88, 65, 54, 44, 45],
    &[48, 49, 61, 72],
    &[49, 50, 62, 73, 58],
    &[50, 51, 63, 74, 69, 59],
    &[51, 52, 75, 86, 70, 60],
    &[52, 64, 87, 71, 61],
    &[64, 76, 72, 62],
    &[65, 77, 83, 62, 52],
    &[66, 78, 84, 73, 52, 53],
    &[67, 79, 74, 63, 53, 54],
    &[68, 75, 64, 54, 55],
    &[76, 65, 55, 56],
];
