use crate::color;
use crate::constants::PromotionPiece;
use crate::hexchess::color::Color;
use crate::hexchess::hexchess::Hexchess;
use crate::hexchess::san::San;
use smallvec::SmallVec;

/** pre-computed position pawn graph */
struct PawnGraph {
    forward_1: u8,
    forward_2: Option<u8>,
    capture_portside: Option<u8>,
    capture_starboard: Option<u8>,
    promote_forward: bool,
    promote_portside: bool,
    promote_starboard: bool,
}

/** pre-computed positions for white pawns */
const WHITE_PAWN_GRAPH: [Option<PawnGraph>; 91] = [
    None,
    None,
    Some(PawnGraph {
        forward_1: 0,
        forward_2: None,
        capture_portside: Some(1),
        capture_starboard: Some(3),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: true
    }),
    None,
    None,
    Some(PawnGraph {
        forward_1: 1,
        forward_2: None,
        capture_portside: Some(4),
        capture_starboard: Some(2),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 2,
        forward_2: None,
        capture_portside: Some(5),
        capture_starboard: Some(7),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 3,
        forward_2: None,
        capture_portside: Some(2),
        capture_starboard: Some(8),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    None,
    None,
    Some(PawnGraph {
        forward_1: 4,
        forward_2: None,
        capture_portside: Some(9),
        capture_starboard: Some(5),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 5,
        forward_2: None,
        capture_portside: Some(10),
        capture_starboard: Some(6),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 6,
        forward_2: None,
        capture_portside: Some(11),
        capture_starboard: Some(13),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 7,
        forward_2: None,
        capture_portside: Some(6),
        capture_starboard: Some(14),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 8,
        forward_2: None,
        capture_portside: Some(7),
        capture_starboard: Some(15),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    None,
    None,
    Some(PawnGraph {
        forward_1: 9,
        forward_2: None,
        capture_portside: Some(16),
        capture_starboard: Some(10),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 10,
        forward_2: None,
        capture_portside: Some(17),
        capture_starboard: Some(11),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 11,
        forward_2: None,
        capture_portside: Some(18),
        capture_starboard: Some(12),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 12,
        forward_2: None,
        capture_portside: Some(19),
        capture_starboard: Some(21),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 13,
        forward_2: None,
        capture_portside: Some(12),
        capture_starboard: Some(22),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 14,
        forward_2: None,
        capture_portside: Some(13),
        capture_starboard: Some(23),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 15,
        forward_2: None,
        capture_portside: Some(14),
        capture_starboard: Some(24),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    None,
    None,
    Some(PawnGraph {
        forward_1: 16,
        forward_2: None,
        capture_portside: Some(25),
        capture_starboard: Some(17),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 17,
        forward_2: None,
        capture_portside: Some(26),
        capture_starboard: Some(18),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 18,
        forward_2: None,
        capture_portside: Some(27),
        capture_starboard: Some(19),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 19,
        forward_2: None,
        capture_portside: Some(28),
        capture_starboard: Some(20),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 20,
        forward_2: None,
        capture_portside: Some(29),
        capture_starboard: Some(31),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 21,
        forward_2: None,
        capture_portside: Some(20),
        capture_starboard: Some(32),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 22,
        forward_2: None,
        capture_portside: Some(21),
        capture_starboard: Some(33),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 23,
        forward_2: None,
        capture_portside: Some(22),
        capture_starboard: Some(34),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 24,
        forward_2: None,
        capture_portside: Some(23),
        capture_starboard: Some(35),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    None,
    Some(PawnGraph {
        forward_1: 25,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(26),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 26,
        forward_2: None,
        capture_portside: Some(36),
        capture_starboard: Some(27),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 27,
        forward_2: None,
        capture_portside: Some(37),
        capture_starboard: Some(28),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 28,
        forward_2: None,
        capture_portside: Some(38),
        capture_starboard: Some(29),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 29,
        forward_2: None,
        capture_portside: Some(39),
        capture_starboard: Some(30),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 30,
        forward_2: Some(20),
        capture_portside: Some(40),
        capture_starboard: Some(42),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 31,
        forward_2: None,
        capture_portside: Some(30),
        capture_starboard: Some(43),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 32,
        forward_2: None,
        capture_portside: Some(31),
        capture_starboard: Some(44),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 33,
        forward_2: None,
        capture_portside: Some(32),
        capture_starboard: Some(45),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 34,
        forward_2: None,
        capture_portside: Some(33),
        capture_starboard: Some(46),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 35,
        forward_2: None,
        capture_portside: Some(34),
        capture_starboard: None,
        promote_forward: true,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 36,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(37),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 37,
        forward_2: None,
        capture_portside: Some(47),
        capture_starboard: Some(38),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 38,
        forward_2: None,
        capture_portside: Some(48),
        capture_starboard: Some(39),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 39,
        forward_2: None,
        capture_portside: Some(49),
        capture_starboard: Some(40),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 40,
        forward_2: Some(29),
        capture_portside: Some(50),
        capture_starboard: Some(41),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    None,
    Some(PawnGraph {
        forward_1: 42,
        forward_2: Some(31),
        capture_portside: Some(41),
        capture_starboard: Some(54),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 43,
        forward_2: None,
        capture_portside: Some(42),
        capture_starboard: Some(55),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 44,
        forward_2: None,
        capture_portside: Some(43),
        capture_starboard: Some(56),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 45,
        forward_2: None,
        capture_portside: Some(44),
        capture_starboard: Some(57),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 46,
        forward_2: None,
        capture_portside: Some(45),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 47,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(48),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 48,
        forward_2: None,
        capture_portside: Some(58),
        capture_starboard: Some(49),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 49,
        forward_2: None,
        capture_portside: Some(59),
        capture_starboard: Some(50),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 50,
        forward_2: Some(39),
        capture_portside: Some(60),
        capture_starboard: Some(51),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    None,
    None,
    None,
    Some(PawnGraph {
        forward_1: 54,
        forward_2: Some(43),
        capture_portside: Some(53),
        capture_starboard: Some(66),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 55,
        forward_2: None,
        capture_portside: Some(54),
        capture_starboard: Some(67),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 56,
        forward_2: None,
        capture_portside: Some(55),
        capture_starboard: Some(68),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 57,
        forward_2: None,
        capture_portside: Some(56),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 58,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(59),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 59,
        forward_2: None,
        capture_portside: Some(69),
        capture_starboard: Some(60),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 60,
        forward_2: Some(49),
        capture_portside: Some(70),
        capture_starboard: Some(61),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    None,
    None,
    None,
    None,
    None,
    Some(PawnGraph {
        forward_1: 66,
        forward_2: Some(55),
        capture_portside: Some(65),
        capture_starboard: Some(78),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 67,
        forward_2: None,
        capture_portside: Some(66),
        capture_starboard: Some(79),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 68,
        forward_2: None,
        capture_portside: Some(67),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 69,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(70),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 70,
        forward_2: Some(59),
        capture_portside: Some(80),
        capture_starboard: Some(71),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(PawnGraph {
        forward_1: 78,
        forward_2: Some(67),
        capture_portside: Some(77),
        capture_starboard: Some(90),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 79,
        forward_2: None,
        capture_portside: Some(78),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
];

/** pre-computed positions for black pawns */
const BLACK_PAWN_GRAPH: [Option<PawnGraph>; 91] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(PawnGraph {
        forward_1: 26,
        forward_2: Some(37),
        capture_portside: Some(17),
        capture_starboard: Some(25),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 27,
        forward_2: Some(38),
        capture_portside: Some(18),
        capture_starboard: Some(26),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 28,
        forward_2: Some(39),
        capture_portside: Some(19),
        capture_starboard: Some(27),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 29,
        forward_2: Some(40),
        capture_portside: Some(20),
        capture_starboard: Some(28),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 30,
        forward_2: Some(41),
        capture_portside: Some(31),
        capture_starboard: Some(29),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 31,
        forward_2: Some(42),
        capture_portside: Some(32),
        capture_starboard: Some(20),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 32,
        forward_2: Some(43),
        capture_portside: Some(33),
        capture_starboard: Some(21),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 33,
        forward_2: Some(44),
        capture_portside: Some(34),
        capture_starboard: Some(22),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 34,
        forward_2: Some(45),
        capture_portside: Some(35),
        capture_starboard: Some(23),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 36,
        forward_2: None,
        capture_portside: Some(26),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 37,
        forward_2: None,
        capture_portside: Some(27),
        capture_starboard: Some(36),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 38,
        forward_2: None,
        capture_portside: Some(28),
        capture_starboard: Some(37),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 39,
        forward_2: None,
        capture_portside: Some(29),
        capture_starboard: Some(38),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 40,
        forward_2: None,
        capture_portside: Some(30),
        capture_starboard: Some(39),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 41,
        forward_2: None,
        capture_portside: Some(42),
        capture_starboard: Some(40),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 42,
        forward_2: None,
        capture_portside: Some(43),
        capture_starboard: Some(30),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 43,
        forward_2: None,
        capture_portside: Some(44),
        capture_starboard: Some(31),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 44,
        forward_2: None,
        capture_portside: Some(45),
        capture_starboard: Some(32),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 45,
        forward_2: None,
        capture_portside: Some(46),
        capture_starboard: Some(33),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 46,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(34),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 47,
        forward_2: None,
        capture_portside: Some(37),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 48,
        forward_2: None,
        capture_portside: Some(38),
        capture_starboard: Some(47),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 49,
        forward_2: None,
        capture_portside: Some(39),
        capture_starboard: Some(48),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 50,
        forward_2: None,
        capture_portside: Some(40),
        capture_starboard: Some(49),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 51,
        forward_2: None,
        capture_portside: Some(41),
        capture_starboard: Some(50),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 52,
        forward_2: None,
        capture_portside: Some(53),
        capture_starboard: Some(51),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 53,
        forward_2: None,
        capture_portside: Some(54),
        capture_starboard: Some(41),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 54,
        forward_2: None,
        capture_portside: Some(55),
        capture_starboard: Some(42),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 55,
        forward_2: None,
        capture_portside: Some(56),
        capture_starboard: Some(43),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 56,
        forward_2: None,
        capture_portside: Some(57),
        capture_starboard: Some(44),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 57,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(45),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 58,
        forward_2: None,
        capture_portside: Some(48),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 59,
        forward_2: None,
        capture_portside: Some(49),
        capture_starboard: Some(58),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 60,
        forward_2: None,
        capture_portside: Some(50),
        capture_starboard: Some(59),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 61,
        forward_2: None,
        capture_portside: Some(51),
        capture_starboard: Some(60),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 62,
        forward_2: None,
        capture_portside: Some(52),
        capture_starboard: Some(61),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 63,
        forward_2: None,
        capture_portside: Some(64),
        capture_starboard: Some(62),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 64,
        forward_2: None,
        capture_portside: Some(65),
        capture_starboard: Some(52),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 65,
        forward_2: None,
        capture_portside: Some(66),
        capture_starboard: Some(53),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 66,
        forward_2: None,
        capture_portside: Some(67),
        capture_starboard: Some(54),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 67,
        forward_2: None,
        capture_portside: Some(68),
        capture_starboard: Some(55),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 68,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(56),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 69,
        forward_2: None,
        capture_portside: Some(59),
        capture_starboard: None,
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 70,
        forward_2: None,
        capture_portside: Some(60),
        capture_starboard: Some(69),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 71,
        forward_2: None,
        capture_portside: Some(61),
        capture_starboard: Some(70),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 72,
        forward_2: None,
        capture_portside: Some(62),
        capture_starboard: Some(71),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 73,
        forward_2: None,
        capture_portside: Some(63),
        capture_starboard: Some(72),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 74,
        forward_2: None,
        capture_portside: Some(75),
        capture_starboard: Some(73),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 75,
        forward_2: None,
        capture_portside: Some(76),
        capture_starboard: Some(63),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 76,
        forward_2: None,
        capture_portside: Some(77),
        capture_starboard: Some(64),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 77,
        forward_2: None,
        capture_portside: Some(78),
        capture_starboard: Some(65),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 78,
        forward_2: None,
        capture_portside: Some(79),
        capture_starboard: Some(66),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 79,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(67),
        promote_forward: false,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 80,
        forward_2: None,
        capture_portside: Some(70),
        capture_starboard: None,
        promote_forward: true,
        promote_portside: false,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 81,
        forward_2: None,
        capture_portside: Some(71),
        capture_starboard: Some(80),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    Some(PawnGraph {
        forward_1: 82,
        forward_2: None,
        capture_portside: Some(72),
        capture_starboard: Some(81),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    Some(PawnGraph {
        forward_1: 83,
        forward_2: None,
        capture_portside: Some(73),
        capture_starboard: Some(82),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    Some(PawnGraph {
        forward_1: 84,
        forward_2: None,
        capture_portside: Some(74),
        capture_starboard: Some(83),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: true
    }),
    Some(PawnGraph {
        forward_1: 85,
        forward_2: None,
        capture_portside: Some(86),
        capture_starboard: Some(84),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: true
    }),
    Some(PawnGraph {
        forward_1: 86,
        forward_2: None,
        capture_portside: Some(87),
        capture_starboard: Some(74),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 87,
        forward_2: None,
        capture_portside: Some(88),
        capture_starboard: Some(75),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 88,
        forward_2: None,
        capture_portside: Some(89),
        capture_starboard: Some(76),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 89,
        forward_2: None,
        capture_portside: Some(90),
        capture_starboard: Some(77),
        promote_forward: true,
        promote_portside: true,
        promote_starboard: false,
    }),
    Some(PawnGraph {
        forward_1: 90,
        forward_2: None,
        capture_portside: None,
        capture_starboard: Some(78),
        promote_forward: true,
        promote_portside: false,
        promote_starboard: false,
    }),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];

/** unsafe pawn moves */
pub fn pawn_moves_unsafe(
    hexchess: &Hexchess,
    from: u8,
    color: &Color,
) -> SmallVec<[San; 12]> {
    let pawn_graph = match color {
        Color::White => &WHITE_PAWN_GRAPH,
        Color::Black => &BLACK_PAWN_GRAPH,
    };

    let pawn = match &pawn_graph[from as usize] {
        Some(graph) => graph,
        None => return SmallVec::new(),
    };

    let mut sans: SmallVec<[San; 12]> = SmallVec::new();

    // advance forward one position
    if hexchess.board[pawn.forward_1 as usize] == None {
        push_sans(&mut sans, from, pawn.forward_1, pawn.promote_forward);

        // advance forward another position if possible
        match pawn.forward_2 {
            None => {},
            Some(to) => if hexchess.board[to as usize] == None {
                sans.push(San { from, promotion: None, to });
            }
        }
    }

    // capture portside
    match pawn.capture_portside {
        None => {},
        Some(to) => match hexchess.board[to as usize] {
            None => if hexchess.turn == *color && hexchess.ep == Some(to) {
                sans.push(San { from, promotion: None, to });
            },
            Some(occupying_piece) => if occupying_piece.is_enemy(*color) {
                push_sans(&mut sans, from, to, pawn.promote_portside);
            }
        }
    }

    // capture starboard
    match pawn.capture_starboard {
        None => {},
        Some(to) => match hexchess.board[to as usize] {
            None => if hexchess.turn == *color && hexchess.ep == Some(to) {
                sans.push(San { from, promotion: None, to });
            },
            Some(occupying_piece) => if occupying_piece.is_enemy(*color) {
                push_sans(&mut sans, from, to, pawn.promote_starboard);
            }
        }
    }

    sans
}

fn push_sans(
    sans: &mut SmallVec<[San; 12]>,
    from: u8,
    to: u8,
    promotion: bool,
) {
    if promotion {
        sans.push(San { from, promotion: Some(PromotionPiece::Bishop), to });
        sans.push(San { from, promotion: Some(PromotionPiece::Knight), to });
        sans.push(San { from, promotion: Some(PromotionPiece::Queen), to });
        sans.push(San { from, promotion: Some(PromotionPiece::Rook), to });
    } else {
        sans.push(San { from, promotion: None, to });
    }
}
