export { default as AlphaPieces } from './pieces/AlphaPieces.vue'
export { default as AnarcandyPieces } from './pieces/AnarcandyPieces.vue'
export { default as CalientePieces } from './pieces/CalientePieces.vue'
export { default as CaliforniaPieces } from './pieces/CaliforniaPieces.vue'
export { default as CardinalPieces } from './pieces/CardinalPieces.vue'
export { default as CburnettPieces } from './pieces/CburnettPieces.vue'
// export { default as CelticPieces } from './pieces/CelticPieces.vue'
export { default as Chess7Pieces } from './pieces/Chess7Pieces.vue'
export { default as ChessnutPieces } from './pieces/ChessnutPieces.vue'
export { default as CompanionPieces } from './pieces/CompanionPieces.vue'
// export { default as CookePieces } from './pieces/CookePieces.vue'
export { default as DisguisedPieces } from './pieces/DisguisedPieces.vue'
export { default as DubrovnyPieces } from './pieces/DubrovnyPieces.vue'
// export { default as FantasyPieces } from './pieces/FantasyPieces.vue'
export { default as FiriPieces } from './pieces/FiriPieces.vue'
export { default as FrescaPieces } from './pieces/FrescaPieces.vue'
export { default as GiocoPieces } from './pieces/GiocoPieces.vue'
export { default as GovernorPieces } from './pieces/GovernorPieces.vue'
export { default as HorseyPieces } from './pieces/HorseyPieces.vue'
export { default as IcpiecesPieces } from './pieces/IcpiecesPieces.vue'
export { default as KiwenSuwiPieces } from './pieces/KiwenSuwiPieces.vue'
// export { default as KosalPieces } from './pieces/KosalPieces.vue'
export { default as LeipzigPieces } from './pieces/LeipzigPieces.vue'
export { default as LetterPieces } from './pieces/LetterPieces.vue'
export { default as MaestroPieces } from './pieces/MaestroPieces.vue'
export { default as MeridaPieces } from './pieces/MeridaPieces.vue'
export { default as MonarchyPieces } from './pieces/MonarchyPieces.vue'
export { default as MonoPieces } from './pieces/MonoPieces.vue'
export { default as MpchessPieces } from './pieces/MpchessPieces.vue'
export { default as PirouettiPieces } from './pieces/PirouettiPieces.vue'
export { default as PixelPieces } from './pieces/PixelPieces.vue'
export { default as ReillycraigPieces } from './pieces/ReillycraigPieces.vue'
// export { default as RhosgfxPieces } from './pieces/RhosgfxPieces.vue'
export { default as RiohachaPieces } from './pieces/RiohachaPieces.vue'
export { default as ShapesPieces } from './pieces/ShapesPieces.vue'
// export { default as SpatialPieces } from './pieces/SpatialPieces.vue'
export { default as StauntyPieces } from './pieces/StauntyPieces.vue'
export { default as TatianaPieces } from './pieces/TatianaPieces.vue'
export { default as XkcdPieces } from './pieces/XkcdPieces.vue'
export { default as Hexboard } from './hexboard/Hexboard.vue'
