[package]
authors = ["Scott Bedard"]
description = "A library for Gliński's hexagonal chess, and the brain of hexchess.club"
edition = "2021"
license = "MIT"
name = "hexchess"
readme = "README.md"
repository = "https://github.com/scottbedard/hexchess"
version = "2.4.1"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bench]]
harness = true
name = "bench_initial_position"
path = "benches/bench_initial_position.rs"

[features]
default = []

[dependencies]
hexchess_macros = { path = "./macros", version = "1" }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
