use hexchess::{Color, Hexchess, Position};

macro_rules! calc_advancement_bonus {
    ($position:expr, $color:expr) => {
        10.0 * match ($position, $color) {
            (Position::A6, Color::Black) => 0.2,
            (Position::B6, Color::Black) => 0.2,
            (Position::C6, Color::Black) => 0.2,
            (Position::D6, Color::Black) => 0.2,
            (Position::E6, Color::Black) => 0.2,
            (Position::F6, Color::Black) => 0.2,
            (Position::G6, Color::Black) => 0.2,
            (Position::H6, Color::Black) => 0.2,
            (Position::I6, Color::Black) => 0.2,
            (Position::K6, Color::Black) => 0.2,
            (Position::L6, Color::Black) => 0.2,
            (Position::A5, Color::Black) => 0.4,
            (Position::B5, Color::Black) => 0.4,
            (Position::C5, Color::Black) => 0.4,
            (Position::D5, Color::Black) => 0.4,
            (Position::E5, Color::Black) => 0.4,
            (Position::F5, Color::Black) => 0.4,
            (Position::G5, Color::Black) => 0.4,
            (Position::H5, Color::Black) => 0.4,
            (Position::I5, Color::Black) => 0.4,
            (Position::K5, Color::Black) => 0.4,
            (Position::L5, Color::Black) => 0.4,
            (Position::A4, Color::Black) => 0.6,
            (Position::B4, Color::Black) => 0.6,
            (Position::C4, Color::Black) => 0.6,
            (Position::D4, Color::Black) => 0.6,
            (Position::E4, Color::Black) => 0.6,
            (Position::F4, Color::Black) => 0.6,
            (Position::G4, Color::Black) => 0.6,
            (Position::H4, Color::Black) => 0.6,
            (Position::I4, Color::Black) => 0.6,
            (Position::K4, Color::Black) => 0.6,
            (Position::L4, Color::Black) => 0.6,
            (Position::A3, Color::Black) => 0.8,
            (Position::B3, Color::Black) => 0.8,
            (Position::C3, Color::Black) => 0.8,
            (Position::D3, Color::Black) => 0.8,
            (Position::E3, Color::Black) => 0.8,
            (Position::F3, Color::Black) => 0.8,
            (Position::G3, Color::Black) => 0.8,
            (Position::H3, Color::Black) => 0.8,
            (Position::I3, Color::Black) => 0.8,
            (Position::K3, Color::Black) => 0.8,
            (Position::L3, Color::Black) => 0.8,
            (Position::A2, Color::Black) => 1.0,
            (Position::B2, Color::Black) => 1.0,
            (Position::C2, Color::Black) => 1.0,
            (Position::D2, Color::Black) => 1.0,
            (Position::E2, Color::Black) => 1.0,
            (Position::F2, Color::Black) => 1.0,
            (Position::G2, Color::Black) => 1.0,
            (Position::H2, Color::Black) => 1.0,
            (Position::I2, Color::Black) => 1.0,
            (Position::K2, Color::Black) => 1.0,
            (Position::L2, Color::Black) => 1.0,
            (Position::F10, Color::White) => 1.0,
            (Position::E9, Color::White) => 1.0,
            (Position::F9, Color::White) => 0.8,
            (Position::G9, Color::White) => 1.0,
            (Position::D8, Color::White) => 1.0,
            (Position::E8, Color::White) => 0.8,
            (Position::F8, Color::White) => 0.6,
            (Position::G8, Color::White) => 0.8,
            (Position::H8, Color::White) => 1.0,
            (Position::C7, Color::White) => 1.0,
            (Position::D7, Color::White) => 0.8,
            (Position::E7, Color::White) => 0.6,
            (Position::F7, Color::White) => 0.4,
            (Position::G7, Color::White) => 0.6,
            (Position::H7, Color::White) => 0.8,
            (Position::I7, Color::White) => 1.0,
            (Position::B6, Color::White) => 1.0,
            (Position::C6, Color::White) => 0.8,
            (Position::D6, Color::White) => 0.6,
            (Position::E6, Color::White) => 0.4,
            (Position::F6, Color::White) => 0.2,
            (Position::G6, Color::White) => 0.4,
            (Position::H6, Color::White) => 0.6,
            (Position::I6, Color::White) => 0.8,
            (Position::K6, Color::White) => 1.0,
            (Position::A5, Color::White) => 1.0,
            (Position::B5, Color::White) => 0.8,
            (Position::C5, Color::White) => 0.6,
            (Position::D5, Color::White) => 0.4,
            (Position::E5, Color::White) => 0.2,
            (Position::G5, Color::White) => 0.2,
            (Position::H5, Color::White) => 0.4,
            (Position::I5, Color::White) => 0.6,
            (Position::K5, Color::White) => 0.8,
            (Position::L5, Color::White) => 1.0,
            (Position::A4, Color::White) => 0.8,
            (Position::B4, Color::White) => 0.6,
            (Position::C4, Color::White) => 0.4,
            (Position::D4, Color::White) => 0.2,
            (Position::H4, Color::White) => 0.2,
            (Position::I4, Color::White) => 0.4,
            (Position::K4, Color::White) => 0.6,
            (Position::L4, Color::White) => 0.8,
            (Position::A3, Color::White) => 0.6,
            (Position::B3, Color::White) => 0.4,
            (Position::C3, Color::White) => 0.2,
            (Position::I3, Color::White) => 0.2,
            (Position::K3, Color::White) => 0.4,
            (Position::L3, Color::White) => 0.6,
            (Position::A2, Color::White) => 0.4,
            (Position::B2, Color::White) => 0.2,
            (Position::K2, Color::White) => 0.2,
            (Position::L2, Color::White) => 0.4,
            (Position::A1, Color::White) => 0.2,
            (Position::L1, Color::White) => 0.2,
            _ => 0.0,
        }
    };
}

pub fn evaluate_pawn(_hexchess: &Hexchess, index: u8, color: Color) -> f32 {
    let position = Position::from_index(index);
    let advancement_bonus = calc_advancement_bonus!(position, color);
    let base_value = 10.0;

    base_value + advancement_bonus
}
