use hexchess::{Color, Hexchess, Position};

pub fn evaluate_pawn(_hexchess: &Hexchess, index: u8, color: Color) -> f32 {
    let position = Position::from_index(index);
    let advancement_bonus = 10.0 * pawn_advancement_scalar(position, color);
    let base_value = 10.0;

    base_value + advancement_bonus
}

/// pawn advancement scalar value.
/// 1.0 = fully advanced, 0.0 = not advanced
fn pawn_advancement_scalar(position: Position, color: Color) -> f32 {
    match color {
        Color::Black => {
            match position {
                Position::A6 => 0.2,
                Position::B6 => 0.2,
                Position::C6 => 0.2,
                Position::D6 => 0.2,
                Position::E6 => 0.2,
                Position::F6 => 0.2,
                Position::G6 => 0.2,
                Position::H6 => 0.2,
                Position::I6 => 0.2,
                Position::K6 => 0.2,
                Position::L6 => 0.2,
                Position::A5 => 0.4,
                Position::B5 => 0.4,
                Position::C5 => 0.4,
                Position::D5 => 0.4,
                Position::E5 => 0.4,
                Position::F5 => 0.4,
                Position::G5 => 0.4,
                Position::H5 => 0.4,
                Position::I5 => 0.4,
                Position::K5 => 0.4,
                Position::L5 => 0.4,
                Position::A4 => 0.6,
                Position::B4 => 0.6,
                Position::C4 => 0.6,
                Position::D4 => 0.6,
                Position::E4 => 0.6,
                Position::F4 => 0.6,
                Position::G4 => 0.6,
                Position::H4 => 0.6,
                Position::I4 => 0.6,
                Position::K4 => 0.6,
                Position::L4 => 0.6,
                Position::A3 => 0.8,
                Position::B3 => 0.8,
                Position::C3 => 0.8,
                Position::D3 => 0.8,
                Position::E3 => 0.8,
                Position::F3 => 0.8,
                Position::G3 => 0.8,
                Position::H3 => 0.8,
                Position::I3 => 0.8,
                Position::K3 => 0.8,
                Position::L3 => 0.8,
                Position::A2 => 1.0,
                Position::B2 => 1.0,
                Position::C2 => 1.0,
                Position::D2 => 1.0,
                Position::E2 => 1.0,
                Position::F2 => 1.0,
                Position::G2 => 1.0,
                Position::H2 => 1.0,
                Position::I2 => 1.0,
                Position::K2 => 1.0,
                Position::L2 => 1.0,
                _ => 0.0,
            }
        },
        Color::White => {
            match position {
                Position::F10 => 1.0,
                Position::E9 => 1.0,
                Position::F9 => 0.8,
                Position::G9 => 1.0,
                Position::D8 => 1.0,
                Position::E8 => 0.8,
                Position::F8 => 0.6,
                Position::G8 => 0.8,
                Position::H8 => 1.0,
                Position::C7 => 1.0,
                Position::D7 => 0.8,
                Position::E7 => 0.6,
                Position::F7 => 0.4,
                Position::G7 => 0.6,
                Position::H7 => 0.8,
                Position::I7 => 1.0,
                Position::B6 => 1.0,
                Position::C6 => 0.8,
                Position::D6 => 0.6,
                Position::E6 => 0.4,
                Position::F6 => 0.2,
                Position::G6 => 0.4,
                Position::H6 => 0.6,
                Position::I6 => 0.8,
                Position::K6 => 1.0,
                Position::A5 => 1.0,
                Position::B5 => 0.8,
                Position::C5 => 0.6,
                Position::D5 => 0.4,
                Position::E5 => 0.2,
                Position::G5 => 0.2,
                Position::H5 => 0.4,
                Position::I5 => 0.6,
                Position::K5 => 0.8,
                Position::L5 => 1.0,
                Position::A4 => 0.8,
                Position::B4 => 0.6,
                Position::C4 => 0.4,
                Position::D4 => 0.2,
                Position::H4 => 0.2,
                Position::I4 => 0.4,
                Position::K4 => 0.6,
                Position::L4 => 0.8,
                Position::A3 => 0.6,
                Position::B3 => 0.4,
                Position::C3 => 0.2,
                Position::I3 => 0.2,
                Position::K3 => 0.4,
                Position::L3 => 0.6,
                Position::A2 => 0.4,
                Position::B2 => 0.2,
                Position::K2 => 0.2,
                Position::L2 => 0.4,
                Position::A1 => 0.2,
                Position::L1 => 0.2,
                _ => 0.0,
            }
        },
        _ => 0.0,
    }
}
