/*
    null,   null,   null,   null,   null,   'f11',  'g10',  'h9',   'i8',   'k7',   'l6',
    null,   null,   null,   null,   'e10',  'f10',  'g9',   'h8',   'i7',   'k6',   'l5',
    null,   null,   null,   'd9',   'e9',   'f9',   'g8',   'h7',   'i6',   'k5',   'l4',
    null,   null,   'c8',   'd8',   'e8',   'f8',   'g7',   'h6',   'i5',   'k4',   'l3',
    null,   'b7',   'c7',   'd7',   'e7',   'f7',   'g6',   'h5',   'i4',   'k3',   'l2',
    'a6',   'b6',   'c6',   'd6',   'e6',   'f6',   'g5',   'h4',   'i3',   'k2',   'l1',
    'a5',   'b5',   'c5',   'd5',   'e5',   'f5',   'g4',   'h3',   'i2',   'k1',   null,
    'a4',   'b4',   'c4',   'd4',   'e4',   'f4',   'g3',   'h2',   'i1',   null,   null,
    'a3',   'b3',   'c3',   'd3',   'e3',   'f3',   'g2',   'h1',   null,   null,   null,
    'a2',   'b2',   'c2',   'd2',   'e2',   'f2',   'g1',   null,   null,   null,   null,
    'a1',   'b1',   'c1',   'd1',   'e1',   'f1',   null,   null,   null,   null,   null,
*/

/// Position within a hexchess bitboard.
#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum Position {
    F11 = 5,
    G10 = 6,
    H9 = 7,
    I8 = 8,
    K7 = 9,
    L6 = 10,
    E10 = 15,
    F10 = 16,
    G9 = 17,
    H8 = 18,
    I7 = 19,
    K6 = 20,
    L5 = 21,
    D9 = 25,
    E9 = 26,
    F9 = 27,
    G8 = 28,
    H7 = 29,
    I6 = 30,
    K5 = 31,
    L4 = 32,
    C8 = 35,
    D8 = 36,
    E8 = 37,
    F8 = 38,
    G7 = 39,
    H6 = 40,
    I5 = 41,
    K4 = 42,
    L3 = 43,
    B7 = 45,
    C7 = 46,
    D7 = 47,
    E7 = 48,
    F7 = 49,
    G6 = 50,
    H5 = 51,
    I4 = 52,
    K3 = 53,
    L2 = 54,
    A6 = 55,
    B6 = 56,
    C6 = 57,
    D6 = 58,
    E6 = 59,
    F6 = 60,
    G5 = 61,
    H4 = 62,
    I3 = 63,
    K2 = 64,
    L1 = 65,
    A5 = 66,
    B5 = 67,
    C5 = 68,
    D5 = 69,
    E5 = 70,
    F5 = 71,
    G4 = 72,
    H3 = 73,
    I2 = 74,
    K1 = 75,
    A4 = 77,
    B4 = 78,
    C4 = 79,
    D4 = 80,
    E4 = 81,
    F4 = 82,
    G3 = 83,
    H2 = 84,
    I1 = 85,
    A3 = 88,
    B3 = 89,
    C3 = 90,
    D3 = 91,
    E3 = 92,
    F3 = 93,
    G2 = 94,
    H1 = 95,
    A2 = 99,
    B2 = 100,
    C2 = 101,
    D2 = 102,
    E2 = 103,
    F2 = 104,
    G1 = 105,
    A1 = 110,
    B1 = 111,
    C1 = 112,
    D1 = 113,
    E1 = 114,
    F1 = 115,
}

impl Position {
    /// Convert FEN index to `Position`.
    pub fn from_index(index: u8) -> Result<Self, ()> {
        match index {
            0 => Ok(Position::F11),
            1 => Ok(Position::E10),
            2 => Ok(Position::F10),
            3 => Ok(Position::G10),
            4 => Ok(Position::D9),
            5 => Ok(Position::E9),
            6 => Ok(Position::F9),
            7 => Ok(Position::G9),
            8 => Ok(Position::H9),
            9 => Ok(Position::C8),
            10 => Ok(Position::D8),
            11 => Ok(Position::E8),
            12 => Ok(Position::F8),
            13 => Ok(Position::G8),
            14 => Ok(Position::H8),
            15 => Ok(Position::I8),
            16 => Ok(Position::B7),
            17 => Ok(Position::C7),
            18 => Ok(Position::D7),
            19 => Ok(Position::E7),
            20 => Ok(Position::F7),
            21 => Ok(Position::G7),
            22 => Ok(Position::H7),
            23 => Ok(Position::I7),
            24 => Ok(Position::K7),
            25 => Ok(Position::A6),
            26 => Ok(Position::B6),
            27 => Ok(Position::C6),
            28 => Ok(Position::D6),
            29 => Ok(Position::E6),
            30 => Ok(Position::F6),
            31 => Ok(Position::G6),
            32 => Ok(Position::H6),
            33 => Ok(Position::I6),
            34 => Ok(Position::K6),
            35 => Ok(Position::L6),
            36 => Ok(Position::A5),
            37 => Ok(Position::B5),
            38 => Ok(Position::C5),
            39 => Ok(Position::D5),
            40 => Ok(Position::E5),
            41 => Ok(Position::F5),
            42 => Ok(Position::G5),
            43 => Ok(Position::H5),
            44 => Ok(Position::I5),
            45 => Ok(Position::K5),
            46 => Ok(Position::L5),
            47 => Ok(Position::A4),
            48 => Ok(Position::B4),
            49 => Ok(Position::C4),
            50 => Ok(Position::D4),
            51 => Ok(Position::E4),
            52 => Ok(Position::F4),
            53 => Ok(Position::G4),
            54 => Ok(Position::H4),
            55 => Ok(Position::I4),
            56 => Ok(Position::K4),
            57 => Ok(Position::L4),
            58 => Ok(Position::A3),
            59 => Ok(Position::B3),
            60 => Ok(Position::C3),
            61 => Ok(Position::D3),
            62 => Ok(Position::E3),
            63 => Ok(Position::F3),
            64 => Ok(Position::G3),
            65 => Ok(Position::H3),
            66 => Ok(Position::I3),
            67 => Ok(Position::K3),
            68 => Ok(Position::L3),
            69 => Ok(Position::A2),
            70 => Ok(Position::B2),
            71 => Ok(Position::C2),
            72 => Ok(Position::D2),
            73 => Ok(Position::E2),
            74 => Ok(Position::F2),
            75 => Ok(Position::G2),
            76 => Ok(Position::H2),
            77 => Ok(Position::I2),
            78 => Ok(Position::K2),
            79 => Ok(Position::L2),
            80 => Ok(Position::A1),
            81 => Ok(Position::B1),
            82 => Ok(Position::C1),
            83 => Ok(Position::D1),
            84 => Ok(Position::E1),
            85 => Ok(Position::F1),
            86 => Ok(Position::G1),
            87 => Ok(Position::H1),
            88 => Ok(Position::I1),
            89 => Ok(Position::K1),
            90 => Ok(Position::L1),
            _ => Err(()),
        }
    }

    /// Convert string to `Position`.
    pub fn from_string(source: &str) -> Result<Self, ()> {
        match source {
            "f11" => Ok(Position::F11),
            "g10" => Ok(Position::G10),
            "h9" => Ok(Position::H9),
            "i8" => Ok(Position::I8),
            "k7" => Ok(Position::K7),
            "l6" => Ok(Position::L6),
            "e10" => Ok(Position::E10),
            "f10" => Ok(Position::F10),
            "g9" => Ok(Position::G9),
            "h8" => Ok(Position::H8),
            "i7" => Ok(Position::I7),
            "k6" => Ok(Position::K6),
            "l5" => Ok(Position::L5),
            "d9" => Ok(Position::D9),
            "e9" => Ok(Position::E9),
            "f9" => Ok(Position::F9),
            "g8" => Ok(Position::G8),
            "h7" => Ok(Position::H7),
            "i6" => Ok(Position::I6),
            "k5" => Ok(Position::K5),
            "l4" => Ok(Position::L4),
            "c8" => Ok(Position::C8),
            "d8" => Ok(Position::D8),
            "e8" => Ok(Position::E8),
            "f8" => Ok(Position::F8),
            "g7" => Ok(Position::G7),
            "h6" => Ok(Position::H6),
            "i5" => Ok(Position::I5),
            "k4" => Ok(Position::K4),
            "l3" => Ok(Position::L3),
            "b7" => Ok(Position::B7),
            "c7" => Ok(Position::C7),
            "d7" => Ok(Position::D7),
            "e7" => Ok(Position::E7),
            "f7" => Ok(Position::F7),
            "g6" => Ok(Position::G6),
            "h5" => Ok(Position::H5),
            "i4" => Ok(Position::I4),
            "k3" => Ok(Position::K3),
            "l2" => Ok(Position::L2),
            "a6" => Ok(Position::A6),
            "b6" => Ok(Position::B6),
            "c6" => Ok(Position::C6),
            "d6" => Ok(Position::D6),
            "e6" => Ok(Position::E6),
            "f6" => Ok(Position::F6),
            "g5" => Ok(Position::G5),
            "h4" => Ok(Position::H4),
            "i3" => Ok(Position::I3),
            "k2" => Ok(Position::K2),
            "l1" => Ok(Position::L1),
            "a5" => Ok(Position::A5),
            "b5" => Ok(Position::B5),
            "c5" => Ok(Position::C5),
            "d5" => Ok(Position::D5),
            "e5" => Ok(Position::E5),
            "f5" => Ok(Position::F5),
            "g4" => Ok(Position::G4),
            "h3" => Ok(Position::H3),
            "i2" => Ok(Position::I2),
            "k1" => Ok(Position::K1),
            "a4" => Ok(Position::A4),
            "b4" => Ok(Position::B4),
            "c4" => Ok(Position::C4),
            "d4" => Ok(Position::D4),
            "e4" => Ok(Position::E4),
            "f4" => Ok(Position::F4),
            "g3" => Ok(Position::G3),
            "h2" => Ok(Position::H2),
            "i1" => Ok(Position::I1),
            "a3" => Ok(Position::A3),
            "b3" => Ok(Position::B3),
            "c3" => Ok(Position::C3),
            "d3" => Ok(Position::D3),
            "e3" => Ok(Position::E3),
            "f3" => Ok(Position::F3),
            "g2" => Ok(Position::G2),
            "h1" => Ok(Position::H1),
            "a2" => Ok(Position::A2),
            "b2" => Ok(Position::B2),
            "c2" => Ok(Position::C2),
            "d2" => Ok(Position::D2),
            "e2" => Ok(Position::E2),
            "f2" => Ok(Position::F2),
            "g1" => Ok(Position::G1),
            "a1" => Ok(Position::A1),
            "b1" => Ok(Position::B1),
            "c1" => Ok(Position::C1),
            "d1" => Ok(Position::D1),
            "e1" => Ok(Position::E1),
            "f1" => Ok(Position::F1),
            _ => Err(()),
        }
    }
}
