use std::fmt;
use serde::{Deserialize, Serialize};

/*
    null,   null,   null,   null,   null,   'f11',  'g10',  'h9',   'i8',   'k7',   'l6',
    null,   null,   null,   null,   'e10',  'f10',  'g9',   'h8',   'i7',   'k6',   'l5',
    null,   null,   null,   'd9',   'e9',   'f9',   'g8',   'h7',   'i6',   'k5',   'l4',
    null,   null,   'c8',   'd8',   'e8',   'f8',   'g7',   'h6',   'i5',   'k4',   'l3',
    null,   'b7',   'c7',   'd7',   'e7',   'f7',   'g6',   'h5',   'i4',   'k3',   'l2',
    'a6',   'b6',   'c6',   'd6',   'e6',   'f6',   'g5',   'h4',   'i3',   'k2',   'l1',
    'a5',   'b5',   'c5',   'd5',   'e5',   'f5',   'g4',   'h3',   'i2',   'k1',   null,
    'a4',   'b4',   'c4',   'd4',   'e4',   'f4',   'g3',   'h2',   'i1',   null,   null,
    'a3',   'b3',   'c3',   'd3',   'e3',   'f3',   'g2',   'h1',   null,   null,   null,
    'a2',   'b2',   'c2',   'd2',   'e2',   'f2',   'g1',   null,   null,   null,   null,
    'a1',   'b1',   'c1',   'd1',   'e1',   'f1',   null,   null,   null,   null,   null,
*/

/// Position within a hexchess bitboard.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[repr(u8)]
pub enum Position {
    F11 = 5,
    G10 = 6,
    H9 = 7,
    I8 = 8,
    K7 = 9,
    L6 = 10,
    E10 = 15,
    F10 = 16,
    G9 = 17,
    H8 = 18,
    I7 = 19,
    K6 = 20,
    L5 = 21,
    D9 = 25,
    E9 = 26,
    F9 = 27,
    G8 = 28,
    H7 = 29,
    I6 = 30,
    K5 = 31,
    L4 = 32,
    C8 = 35,
    D8 = 36,
    E8 = 37,
    F8 = 38,
    G7 = 39,
    H6 = 40,
    I5 = 41,
    K4 = 42,
    L3 = 43,
    B7 = 45,
    C7 = 46,
    D7 = 47,
    E7 = 48,
    F7 = 49,
    G6 = 50,
    H5 = 51,
    I4 = 52,
    K3 = 53,
    L2 = 54,
    A6 = 55,
    B6 = 56,
    C6 = 57,
    D6 = 58,
    E6 = 59,
    F6 = 60,
    G5 = 61,
    H4 = 62,
    I3 = 63,
    K2 = 64,
    L1 = 65,
    A5 = 66,
    B5 = 67,
    C5 = 68,
    D5 = 69,
    E5 = 70,
    F5 = 71,
    G4 = 72,
    H3 = 73,
    I2 = 74,
    K1 = 75,
    A4 = 77,
    B4 = 78,
    C4 = 79,
    D4 = 80,
    E4 = 81,
    F4 = 82,
    G3 = 83,
    H2 = 84,
    I1 = 85,
    A3 = 88,
    B3 = 89,
    C3 = 90,
    D3 = 91,
    E3 = 92,
    F3 = 93,
    G2 = 94,
    H1 = 95,
    A2 = 99,
    B2 = 100,
    C2 = 101,
    D2 = 102,
    E2 = 103,
    F2 = 104,
    G1 = 105,
    A1 = 110,
    B1 = 111,
    C1 = 112,
    D1 = 113,
    E1 = 114,
    F1 = 115,
}

impl Position {
    /// Convert bitboard index to `Position`.
    pub fn from_bitboard_index(index: u8) -> Self {
        match index {
            5 => Position::F11,
            6 => Position::G10,
            7 => Position::H9,
            8 => Position::I8,
            9 => Position::K7,
            10 => Position::L6,
            15 => Position::E10,
            16 => Position::F10,
            17 => Position::G9,
            18 => Position::H8,
            19 => Position::I7,
            20 => Position::K6,
            21 => Position::L5,
            25 => Position::D9,
            26 => Position::E9,
            27 => Position::F9,
            28 => Position::G8,
            29 => Position::H7,
            30 => Position::I6,
            31 => Position::K5,
            32 => Position::L4,
            35 => Position::C8,
            36 => Position::D8,
            37 => Position::E8,
            38 => Position::F8,
            39 => Position::G7,
            40 => Position::H6,
            41 => Position::I5,
            42 => Position::K4,
            43 => Position::L3,
            45 => Position::B7,
            46 => Position::C7,
            47 => Position::D7,
            48 => Position::E7,
            49 => Position::F7,
            50 => Position::G6,
            51 => Position::H5,
            52 => Position::I4,
            53 => Position::K3,
            54 => Position::L2,
            55 => Position::A6,
            56 => Position::B6,
            57 => Position::C6,
            58 => Position::D6,
            59 => Position::E6,
            60 => Position::F6,
            61 => Position::G5,
            62 => Position::H4,
            63 => Position::I3,
            64 => Position::K2,
            65 => Position::L1,
            66 => Position::A5,
            67 => Position::B5,
            68 => Position::C5,
            69 => Position::D5,
            70 => Position::E5,
            71 => Position::F5,
            72 => Position::G4,
            73 => Position::H3,
            74 => Position::I2,
            75 => Position::K1,
            77 => Position::A4,
            78 => Position::B4,
            79 => Position::C4,
            80 => Position::D4,
            81 => Position::E4,
            82 => Position::F4,
            83 => Position::G3,
            84 => Position::H2,
            85 => Position::I1,
            88 => Position::A3,
            89 => Position::B3,
            90 => Position::C3,
            91 => Position::D3,
            92 => Position::E3,
            93 => Position::F3,
            94 => Position::G2,
            95 => Position::H1,
            99 => Position::A2,
            100 => Position::B2,
            101 => Position::C2,
            102 => Position::D2,
            103 => Position::E2,
            104 => Position::F2,
            105 => Position::G1,
            110 => Position::A1,
            111 => Position::B1,
            112 => Position::C1,
            113 => Position::D1,
            114 => Position::E1,
            115 => Position::F1,
            _ => panic!("Invalid bitboard index: {}", index),
        }
    }

    /// Convert FEN index to `Position`.
    pub fn from_fen_index(index: u8) -> Self {
        match index {
            0 => Position::F11,
            1 => Position::E10,
            2 => Position::F10,
            3 => Position::G10,
            4 => Position::D9,
            5 => Position::E9,
            6 => Position::F9,
            7 => Position::G9,
            8 => Position::H9,
            9 => Position::C8,
            10 => Position::D8,
            11 => Position::E8,
            12 => Position::F8,
            13 => Position::G8,
            14 => Position::H8,
            15 => Position::I8,
            16 => Position::B7,
            17 => Position::C7,
            18 => Position::D7,
            19 => Position::E7,
            20 => Position::F7,
            21 => Position::G7,
            22 => Position::H7,
            23 => Position::I7,
            24 => Position::K7,
            25 => Position::A6,
            26 => Position::B6,
            27 => Position::C6,
            28 => Position::D6,
            29 => Position::E6,
            30 => Position::F6,
            31 => Position::G6,
            32 => Position::H6,
            33 => Position::I6,
            34 => Position::K6,
            35 => Position::L6,
            36 => Position::A5,
            37 => Position::B5,
            38 => Position::C5,
            39 => Position::D5,
            40 => Position::E5,
            41 => Position::F5,
            42 => Position::G5,
            43 => Position::H5,
            44 => Position::I5,
            45 => Position::K5,
            46 => Position::L5,
            47 => Position::A4,
            48 => Position::B4,
            49 => Position::C4,
            50 => Position::D4,
            51 => Position::E4,
            52 => Position::F4,
            53 => Position::G4,
            54 => Position::H4,
            55 => Position::I4,
            56 => Position::K4,
            57 => Position::L4,
            58 => Position::A3,
            59 => Position::B3,
            60 => Position::C3,
            61 => Position::D3,
            62 => Position::E3,
            63 => Position::F3,
            64 => Position::G3,
            65 => Position::H3,
            66 => Position::I3,
            67 => Position::K3,
            68 => Position::L3,
            69 => Position::A2,
            70 => Position::B2,
            71 => Position::C2,
            72 => Position::D2,
            73 => Position::E2,
            74 => Position::F2,
            75 => Position::G2,
            76 => Position::H2,
            77 => Position::I2,
            78 => Position::K2,
            79 => Position::L2,
            80 => Position::A1,
            81 => Position::B1,
            82 => Position::C1,
            83 => Position::D1,
            84 => Position::E1,
            85 => Position::F1,
            86 => Position::G1,
            87 => Position::H1,
            88 => Position::I1,
            89 => Position::K1,
            90 => Position::L1,
            _ => panic!("Invalid FEN index: {}", index),
        }
    }

    /// Convert string to `Position`.
    pub fn from_string(source: &str) -> Self {
        match source {
            "f11" => Position::F11,
            "g10" => Position::G10,
            "h9" => Position::H9,
            "i8" => Position::I8,
            "k7" => Position::K7,
            "l6" => Position::L6,
            "e10" => Position::E10,
            "f10" => Position::F10,
            "g9" => Position::G9,
            "h8" => Position::H8,
            "i7" => Position::I7,
            "k6" => Position::K6,
            "l5" => Position::L5,
            "d9" => Position::D9,
            "e9" => Position::E9,
            "f9" => Position::F9,
            "g8" => Position::G8,
            "h7" => Position::H7,
            "i6" => Position::I6,
            "k5" => Position::K5,
            "l4" => Position::L4,
            "c8" => Position::C8,
            "d8" => Position::D8,
            "e8" => Position::E8,
            "f8" => Position::F8,
            "g7" => Position::G7,
            "h6" => Position::H6,
            "i5" => Position::I5,
            "k4" => Position::K4,
            "l3" => Position::L3,
            "b7" => Position::B7,
            "c7" => Position::C7,
            "d7" => Position::D7,
            "e7" => Position::E7,
            "f7" => Position::F7,
            "g6" => Position::G6,
            "h5" => Position::H5,
            "i4" => Position::I4,
            "k3" => Position::K3,
            "l2" => Position::L2,
            "a6" => Position::A6,
            "b6" => Position::B6,
            "c6" => Position::C6,
            "d6" => Position::D6,
            "e6" => Position::E6,
            "f6" => Position::F6,
            "g5" => Position::G5,
            "h4" => Position::H4,
            "i3" => Position::I3,
            "k2" => Position::K2,
            "l1" => Position::L1,
            "a5" => Position::A5,
            "b5" => Position::B5,
            "c5" => Position::C5,
            "d5" => Position::D5,
            "e5" => Position::E5,
            "f5" => Position::F5,
            "g4" => Position::G4,
            "h3" => Position::H3,
            "i2" => Position::I2,
            "k1" => Position::K1,
            "a4" => Position::A4,
            "b4" => Position::B4,
            "c4" => Position::C4,
            "d4" => Position::D4,
            "e4" => Position::E4,
            "f4" => Position::F4,
            "g3" => Position::G3,
            "h2" => Position::H2,
            "i1" => Position::I1,
            "a3" => Position::A3,
            "b3" => Position::B3,
            "c3" => Position::C3,
            "d3" => Position::D3,
            "e3" => Position::E3,
            "f3" => Position::F3,
            "g2" => Position::G2,
            "h1" => Position::H1,
            "a2" => Position::A2,
            "b2" => Position::B2,
            "c2" => Position::C2,
            "d2" => Position::D2,
            "e2" => Position::E2,
            "f2" => Position::F2,
            "g1" => Position::G1,
            "a1" => Position::A1,
            "b1" => Position::B1,
            "c1" => Position::C1,
            "d1" => Position::D1,
            "e1" => Position::E1,
            "f1" => Position::F1,
            _ => panic!("Invalid position: {}", source),
        }
    }

    /// test if position is black promotion position
    pub fn is_black_promotion_position(&self) -> bool {
        match self {
            Position::A1 |
            Position::B1 |
            Position::C1 |
            Position::D1 |
            Position::E1 |
            Position::F1 |
            Position::G1 |
            Position::H1 |
            Position::I1 |
            Position::K1 |
            Position::L1 => true,
            _ => false,
        }
    }

    /// test if position is a white promotion position
    pub fn is_white_promotion_position(&self) -> bool {
        match self {
            Position::F11 |
            Position::E10 |
            Position::G10 |
            Position::D9 |
            Position::H9 |
            Position::C8 |
            Position::I8 |
            Position::B7 |
            Position::K7 |
            Position::A6 |
            Position::L6 => true,
            _ => false,
        }
    }

    /// test if position is a promotion position
    pub fn is_promotion_position(&self) -> bool {
        self.is_black_promotion_position() || self.is_white_promotion_position()
    }

    /// Convert position to FEN index.
    pub fn to_fen_index(&self) -> u8 {
        match self {
            Position::F11 => 0,
            Position::E10 => 1,
            Position::F10 => 2,
            Position::G10 => 3,
            Position::D9 => 4,
            Position::E9 => 5,
            Position::F9 => 6,
            Position::G9 => 7,
            Position::H9 => 8,
            Position::C8 => 9,
            Position::D8 => 10,
            Position::E8 => 11,
            Position::F8 => 12,
            Position::G8 => 13,
            Position::H8 => 14,
            Position::I8 => 15,
            Position::B7 => 16,
            Position::C7 => 17,
            Position::D7 => 18,
            Position::E7 => 19,
            Position::F7 => 20,
            Position::G7 => 21,
            Position::H7 => 22,
            Position::I7 => 23,
            Position::K7 => 24,
            Position::A6 => 25,
            Position::B6 => 26,
            Position::C6 => 27,
            Position::D6 => 28,
            Position::E6 => 29,
            Position::F6 => 30,
            Position::G6 => 31,
            Position::H6 => 32,
            Position::I6 => 33,
            Position::K6 => 34,
            Position::L6 => 35,
            Position::A5 => 36,
            Position::B5 => 37,
            Position::C5 => 38,
            Position::D5 => 39,
            Position::E5 => 40,
            Position::F5 => 41,
            Position::G5 => 42,
            Position::H5 => 43,
            Position::I5 => 44,
            Position::K5 => 45,
            Position::L5 => 46,
            Position::A4 => 47,
            Position::B4 => 48,
            Position::C4 => 49,
            Position::D4 => 50,
            Position::E4 => 51,
            Position::F4 => 52,
            Position::G4 => 53,
            Position::H4 => 54,
            Position::I4 => 55,
            Position::K4 => 56,
            Position::L4 => 57,
            Position::A3 => 58,
            Position::B3 => 59,
            Position::C3 => 60,
            Position::D3 => 61,
            Position::E3 => 62,
            Position::F3 => 63,
            Position::G3 => 64,
            Position::H3 => 65,
            Position::I3 => 66,
            Position::K3 => 67,
            Position::L3 => 68,
            Position::A2 => 69,
            Position::B2 => 70,
            Position::C2 => 71,
            Position::D2 => 72,
            Position::E2 => 73,
            Position::F2 => 74,
            Position::G2 => 75,
            Position::H2 => 76,
            Position::I2 => 77,
            Position::K2 => 78,
            Position::L2 => 79,
            Position::A1 => 80,
            Position::B1 => 81,
            Position::C1 => 82,
            Position::D1 => 83,
            Position::E1 => 84,
            Position::F1 => 85,
            Position::G1 => 86,
            Position::H1 => 87,
            Position::I1 => 88,
            Position::K1 => 89,
            Position::L1 => 90,
        }
    }
}

impl fmt::Display for Position {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let position = match self {
            Self::F11 => "f11",
            Self::E10 => "e10",
            Self::F10 => "f10",
            Self::G10 => "g10",
            Self::D9 => "d9",
            Self::E9 => "e9",
            Self::F9 => "f9",
            Self::G9 => "g9",
            Self::H9 => "h9",
            Self::C8 => "c8",
            Self::D8 => "d8",
            Self::E8 => "e8",
            Self::F8 => "f8",
            Self::G8 => "g8",
            Self::H8 => "h8",
            Self::I8 => "i8",
            Self::B7 => "b7",
            Self::C7 => "c7",
            Self::D7 => "d7",
            Self::E7 => "e7",
            Self::F7 => "f7",
            Self::G7 => "g7",
            Self::H7 => "h7",
            Self::I7 => "i7",
            Self::K7 => "k7",
            Self::A6 => "a6",
            Self::B6 => "b6",
            Self::C6 => "c6",
            Self::D6 => "d6",
            Self::E6 => "e6",
            Self::F6 => "f6",
            Self::G6 => "g6",
            Self::H6 => "h6",
            Self::I6 => "i6",
            Self::K6 => "k6",
            Self::L6 => "l6",
            Self::A5 => "a5",
            Self::B5 => "b5",
            Self::C5 => "c5",
            Self::D5 => "d5",
            Self::E5 => "e5",
            Self::F5 => "f5",
            Self::G5 => "g5",
            Self::H5 => "h5",
            Self::I5 => "i5",
            Self::K5 => "k5",
            Self::L5 => "l5",
            Self::A4 => "a4",
            Self::B4 => "b4",
            Self::C4 => "c4",
            Self::D4 => "d4",
            Self::E4 => "e4",
            Self::F4 => "f4",
            Self::G4 => "g4",
            Self::H4 => "h4",
            Self::I4 => "i4",
            Self::K4 => "k4",
            Self::L4 => "l4",
            Self::A3 => "a3",
            Self::B3 => "b3",
            Self::C3 => "c3",
            Self::D3 => "d3",
            Self::E3 => "e3",
            Self::F3 => "f3",
            Self::G3 => "g3",
            Self::H3 => "h3",
            Self::I3 => "i3",
            Self::K3 => "k3",
            Self::L3 => "l3",
            Self::A2 => "a2",
            Self::B2 => "b2",
            Self::C2 => "c2",
            Self::D2 => "d2",
            Self::E2 => "e2",
            Self::F2 => "f2",
            Self::G2 => "g2",
            Self::H2 => "h2",
            Self::I2 => "i2",
            Self::K2 => "k2",
            Self::L2 => "l2",
            Self::A1 => "a1",
            Self::B1 => "b1",
            Self::C1 => "c1",
            Self::D1 => "d1",
            Self::E1 => "e1",
            Self::F1 => "f1",
            Self::G1 => "g1",
            Self::H1 => "h1",
            Self::I1 => "i1",
            Self::K1 => "k1",
            Self::L1 => "l1",
        };
    
        write!(f, "{}", position)
    }
}
