use crate::hexchess::game::Game;
use crate::hexchess::position::Position;
use crate::hexchess::san::San;

pub fn get_moves_unsafe(game: &Game, from: Position) -> Vec<San> {
    let capacity = get_maximum_moves(from);
    let mut result = Vec::with_capacity(capacity as usize);

    result
}

/// maximum number of moves a knight can make from a given position
pub fn get_maximum_moves(from: Position) -> u8 {
    match from {
        Position::F11 => 4,
        Position::E10 => 5,
        Position::F10 => 6,
        Position::G10 => 5,
        Position::D9 => 6,
        Position::E9 => 7,
        Position::F9 => 8,
        Position::G9 => 7,
        Position::H9 => 6,
        Position::C8 => 6,
        Position::D8 => 8,
        Position::E8 => 10,
        Position::F8 => 12,
        Position::G8 => 10,
        Position::H8 => 8,
        Position::I8 => 6,
        Position::B7 => 5,
        Position::C7 => 7,
        Position::D7 => 10,
        Position::E7 => 12,
        Position::F7 => 12,
        Position::G7 => 12,
        Position::H7 => 10,
        Position::I7 => 7,
        Position::K7 => 5,
        Position::A6 => 4,
        Position::B6 => 6,
        Position::C6 => 8,
        Position::D6 => 12,
        Position::E6 => 12,
        Position::F6 => 12,
        Position::G6 => 12,
        Position::H6 => 12,
        Position::I6 => 8,
        Position::K6 => 6,
        Position::L6 => 4,
        Position::A5 => 5,
        Position::B5 => 7,
        Position::C5 => 10,
        Position::D5 => 12,
        Position::E5 => 12,
        Position::F5 => 12,
        Position::G5 => 12,
        Position::H5 => 12,
        Position::I5 => 10,
        Position::K5 => 7,
        Position::L5 => 5,
        Position::A4 => 6,
        Position::B4 => 8,
        Position::C4 => 10,
        Position::D4 => 12,
        Position::E4 => 12,
        Position::F4 => 12,
        Position::G4 => 12,
        Position::H4 => 12,
        Position::I4 => 10,
        Position::K4 => 8,
        Position::L4 => 6,
        Position::A3 => 6,
        Position::B3 => 7,
        Position::C3 => 8,
        Position::D3 => 10,
        Position::E3 => 10,
        Position::F3 => 8,
        Position::G3 => 10,
        Position::H3 => 10,
        Position::I3 => 8,
        Position::K3 => 7,
        Position::L3 => 6,
        Position::A2 => 5,
        Position::B2 => 6,
        Position::C2 => 7,
        Position::D2 => 8,
        Position::E2 => 7,
        Position::F2 => 6,
        Position::G2 => 7,
        Position::H2 => 8,
        Position::I2 => 7,
        Position::K2 => 6,
        Position::L2 => 5,
        Position::A1 => 4,
        Position::B1 => 5,
        Position::C1 => 6,
        Position::D1 => 6,
        Position::E1 => 5,
        Position::F1 => 4,
        Position::G1 => 5,
        Position::H1 => 6,
        Position::I1 => 6,
        Position::K1 => 5,
        Position::L1 => 4,
    }
}