name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          cd js
          pnpm install --no-frozen-lockfile

      - name: Build package
        run: pnpm build --js

      - name: Lint
        run: |
          cd js
          pnpm lint

      - name: Vitest
        run: |
          cd js
          pnpm test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd rust
          cargo build --release

      - name: Test
        run: |
          cd rust
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: pcov
      - name: Install dependencies
        run: |
          cd php
          composer install
      - name: Test
        working-directory: ./php
        run: ./vendor/bin/pest --log-junit ./junit.xml --cache-directory=./.pest/cache --coverage-clover coverage.xml 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  versions:
    name: Check versions

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: Check versions
      run: pnpm check-versions
