name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build docs
        run: node hexchess docs:build

  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          cd js
          pnpm install --no-frozen-lockfile

      - name: Build package
        run: node hexchess build:js

      - name: Vitest
        run: node hexchess test:js --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  rust:
    name: Rust
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          cd js
          pnpm install --no-frozen-lockfile

      - name: Build
        run: node hexchess build:rs

      - name: Test
        run: node hexchess test:rs --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  engine:
    name: Engine
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: node hexchess build:engine
      - name: Test
        run: node hexchess test:engine
  
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: pcov

      - name: Install PHP dependencies
        run: composer install

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install NPM dependencies
        run: |
          pnpm install --no-frozen-lockfile
          cd js
          pnpm install --no-frozen-lockfile
      - name: Lint
        run: node hexchess lint:php
      - name: Test
        run: node hexchess test:php --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  versions:
    name: Check versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Install dependencies
      run: |
        pnpm install --no-frozen-lockfile
        cd js
        pnpm install --no-frozen-lockfile

    - name: Check versions
      run: node hexchess versions
