name: Release Engine

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Update NPM
        run: npm install -g npm@latest
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: node hexchess build:engine
      - name: Test
        run: node hexchess test:engine
      - name: Prepare clean publish directory
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          mkdir engine-publish
          rsync -av --copy-links ./engine/pkg/ engine-publish/ \
            --exclude=.git

      - name: Publish to NPM
        working-directory: engine-publish
        run: npm publish --provenance --access public
