name: Release Libraries

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        run: |
          composer install
          pnpm install
          cd js
          pnpm install

      - name: Test
        run: node hexchess test

  publish:
    needs: test

    name: Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
  
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: dtolnay/rust-toolchain@stable

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
  
      - name: Install dependencies
        run: |
          composer install
          pnpm install
          cd js
          pnpm install

      - name: Check versions
        run: node hexchess version:check --release=${{ github.ref_name }}
  
      - name: Build package
        run: node hexchess build:js

      - name: Prepare clean publish directory
        run: |
          mkdir js-publish
          cp -a --dereference ./js/dist/. js-publish/

      - name: Publish to NPM
        working-directory: js-publish
        run: npm publish --access public

      - name: Publish to Crates.io
        run: |
          cp README.md rust/README.md
          cp LICENSE rust/LICENSE
          cd rust/macros
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
          cd ../
          cargo publish

      - name: Publish to Packagist
        run: |
          curl -X POST https://packagist.org/api/update-package/scottbedard/hexchess \
            -u "${{ secrets.PACKAGIST_USERNAME }}:${{ secrets.PACKAGIST_TOKEN }}"
