name: build

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        run: |
          pnpm install
          cd js
          pnpm install
          cd ../php
          composer install

      - name: Test
        run: pnpm test

  publish:
    needs: test

    name: Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
  
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: dtolnay/rust-toolchain@stable

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
  
      - name: Install dependencies
        run: |
          pnpm install
          cd js
          pnpm install
          cd ../php
          composer install

      - name: Check versions
        run: pnpm check-versions release=${{ github.ref_name }}
  
      # - name: Build package
      #   run: pnpm build

      # - name: Publish to NPM
      #   run: |
      #     cd js/dist
      #     npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish to Crates.io
      #   run: |
      #     cd rust
      #     cargo login ${{ secrets.CARGO_TOKEN }}
      #     cargo publish

      - name: Publish to Packagist
        run: |
          cd php
          curl -X POST -u "${{ secrets.PACKAGIST_USERNAME }}:${{ secrets.PACKAGIST_TOKEN }}" \
            https://packagist.org/api/update-package \
            -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/scottbedard/hexchess"}}'
